version: '3.8'

x-gpu-runtime: &gpu-runtime
  # Ce bloc est une référence YAML qui sera utilisée conditionnellement
  runtime: nvidia
  environment:
    - NVIDIA_VISIBLE_DEVICES=all
    - TF_FORCE_GPU_ALLOW_GROWTH=true

services:
  # Base de données PostgreSQL
  postgres:
    image: postgres:14-alpine
    container_name: evil2root-postgres
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: evil2root
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # API FastAPI
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: evil2root-api
    restart: unless-stopped
    volumes:
      - ./:/app
      - ./logs:/app/logs
    environment:
      - DEBUG=true
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=evil2root
      - DB_TYPE=postgresql
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
    command: uvicorn src.api.app:create_app --host 0.0.0.0 --port 8000 --reload

  # Frontend React
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: evil2root-frontend
    restart: unless-stopped
    ports:
      - "3000:80"
    depends_on:
      - api
    volumes:
      - ./frontend/nginx:/etc/nginx/conf.d

  # Service pour les migrations de base de données
  migrations:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: evil2root-migrations
    restart: "no"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=evil2root
      - DB_TYPE=postgresql
    depends_on:
      postgres:
        condition: service_healthy
    command: alembic upgrade head

  # PgAdmin (optionnel, pour la gestion de la base de données)
  pgadmin:
    image: dpage/pgadmin4
    container_name: evil2root-pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@evil2root.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    volumes:
      - pgadmin_data:/var/lib/pgadmin

# Définition des secrets
secrets:
  db_user:
    file: ./secrets/db_user.txt
  db_password:
    file: ./secrets/db_password.txt
  secret_key:
    file: ./secrets/secret_key.txt
  admin_password:
    file: ./secrets/admin_password.txt
  telegram_token:
    file: ./secrets/telegram_token.txt
  finnhub_api_key:
    file: ./secrets/finnhub_api_key.txt
  openrouter_api_key:
    file: ./secrets/openrouter_api_key.txt
  coinbase_api_key:
    file: ./secrets/coinbase_api_key.txt
  coinbase_webhook_secret:
    file: ./secrets/coinbase_webhook_secret.txt

volumes:
  postgres_data:
  pgadmin_data:

networks:
  evil2root-network:
    driver: bridge
