[build]
builder = "dockerfile"
buildCommand = "docker/railway-talib-install.sh && python -m pip install --upgrade pip setuptools wheel && pip install -r requirements.txt"

[deploy]
startCommand = "python app/app.py"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "on_failure"

[env]
TA_INCLUDE_PATH = "/usr/include"
TA_LIBRARY_PATH = "/usr/lib"
PORT = "8000"
