apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJyZWdpc3RyeS5kaWdpdGFsb2NlYW4uY29tIjp7ImF1dGgiOiJZbUZ6ZEdsbGJtcGhkbUYxZUVCbmJXRnBiQzVqYjIwNlpHOXdYM1l4WDJJek9HTXdOR0ZsTkRBek4yUTBPV0k0TUdJek4yTTJZVE5tT1dKaFpXVmlNalk0TnpWallUbGxOelZsTVRWaU9Ea3pORGM0TWpGbU5XWmlNelk1WWpZPSJ9fX0=
kind: Secret
metadata:
  annotations:
    digitalocean.com/dosecret-identifier: registry-evil2root-registry
  creationTimestamp: null
  name: registry-evil2root-registry
  namespace: evil2root-trading
type: kubernetes.io/dockerconfigjson
