apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: analysis-bot-pdb
  namespace: evil2root-trading
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: trading-bot
      component: analysis-bot 