apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: trading-bot-web-pdb
  namespace: evil2root-trading
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: trading-bot
      component: web 