apiVersion: v1
kind: ConfigMap
metadata:
  name: trading-bot-config
  namespace: evil2root-trading
data:
  DB_HOST: "postgres"
  DB_PORT: "5432"
  DB_NAME: "trading_bot"
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
  APP_ENV: "development"
  LOG_LEVEL: "DEBUG"
