apiVersion: v1
kind: Secret
metadata:
  name: trading-bot-secrets
  namespace: evil2root-trading
type: Opaque
stringData:
  DB_USER: "postgres"
  DB_PASSWORD: "changeme"
  DB_NAME: "tradingbot"
  REDIS_PASSWORD: "changeme"
  GRAFANA_ADMIN_USER: "admin"
  GRAFANA_ADMIN_PASSWORD: "admin"
  # Ajoutez ici les secrets supplémentaires présents dans votre fichier .env
  # Note: Pour une production réelle, utilisez plutôt des outils comme Vault ou Sealed Secrets 