apiVersion: apps/v1
kind: Deployment
metadata:
  name: adminer
  namespace: evil2root-trading
spec:
  template:
    spec:
      containers:
      - name: adminer
        image: adminer:latest
        resources:
          limits:
            memory: "256Mi"
            cpu: "300m"
          requests:
            memory: "128Mi"
            cpu: "100m"
