apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: evil2root-trading
spec:
  template:
    spec:
      containers:
      - name: postgres
        image: postgres:13
        resources:
          limits:
            memory: "1Gi"
            cpu: "500m"
          requests:
            memory: "512Mi"
            cpu: "250m"
