apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: evil2root-trading
spec:
  template:
    spec:
      containers:
      - name: redis
        image: redis:6
        resources:
          limits:
            memory: "512Mi"
            cpu: "300m"
          requests:
            memory: "256Mi"
            cpu: "100m"
