apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: prometheuses.monitoring.coreos.com
spec:
  group: monitoring.coreos.com
  names:
    kind: Prometheus
    listKind: PrometheusList
    plural: prometheuses
    singular: prometheus
  scope: Namespaced
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        properties:
          spec:
            properties:
              serviceAccountName:
                type: string
              serviceMonitorSelector:
                type: object
                properties:
                  matchLabels:
                    type: object
                    x-kubernetes-preserve-unknown-fields: true
              podMonitorSelector:
                type: object
              replicas:
                type: integer
              resources:
                type: object
                properties:
                  limits:
                    type: object
                    x-kubernetes-preserve-unknown-fields: true
                  requests:
                    type: object
                    x-kubernetes-preserve-unknown-fields: true
              version:
                type: string
              retention:
                type: string
              securityContext:
                type: object
                x-kubernetes-preserve-unknown-fields: true
              storage:
                type: object
                properties:
                  volumeClaimTemplate:
                    type: object
                    x-kubernetes-preserve-unknown-fields: true
              ruleSelector:
                type: object
                properties:
                  matchLabels:
                    type: object
                    x-kubernetes-preserve-unknown-fields: true
            type: object
        type: object
    served: true
    storage: true
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: servicemonitors.monitoring.coreos.com
spec:
  group: monitoring.coreos.com
  names:
    kind: ServiceMonitor
    listKind: ServiceMonitorList
    plural: servicemonitors
    singular: servicemonitor
  scope: Namespaced
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        properties:
          spec:
            properties:
              endpoints:
                type: array
                items:
                  type: object
                  properties:
                    port:
                      type: string
                    path:
                      type: string
                    interval:
                      type: string
              namespaceSelector:
                type: object
                properties:
                  matchNames:
                    type: array
                    items:
                      type: string
              selector:
                type: object
                properties:
                  matchLabels:
                    type: object
                    x-kubernetes-preserve-unknown-fields: true
            type: object
        type: object
    served: true
    storage: true
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: podmonitors.monitoring.coreos.com
spec:
  group: monitoring.coreos.com
  names:
    kind: PodMonitor
    listKind: PodMonitorList
    plural: podmonitors
    singular: podmonitor
  scope: Namespaced
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        properties:
          spec:
            properties:
              podMetricsEndpoints:
                type: array
                items:
                  type: object
                  properties:
                    port:
                      type: string
                    path:
                      type: string
                    interval:
                      type: string
              selector:
                type: object
            type: object
        type: object
    served: true
    storage: true
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: prometheusrules.monitoring.coreos.com
spec:
  group: monitoring.coreos.com
  names:
    kind: PrometheusRule
    listKind: PrometheusRuleList
    plural: prometheusrules
    singular: prometheusrule
  scope: Namespaced
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        properties:
          spec:
            properties:
              groups:
                type: array
                items:
                  type: object
                  properties:
                    name:
                      type: string
                    rules:
                      type: array
                      items:
                        type: object
                        properties:
                          alert:
                            type: string
                          expr:
                            type: string
                          for:
                            type: string
                          labels:
                            type: object
                            properties:
                              severity:
                                type: string
                            x-kubernetes-preserve-unknown-fields: true
                          annotations:
                            type: object
                            properties:
                              summary:
                                type: string
                              description:
                                type: string
                            x-kubernetes-preserve-unknown-fields: true
            type: object
        type: object
    served: true
    storage: true
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: alertmanagers.monitoring.coreos.com
spec:
  group: monitoring.coreos.com
  names:
    kind: Alertmanager
    listKind: AlertmanagerList
    plural: alertmanagers
    singular: alertmanager
  scope: Namespaced
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        properties:
          spec:
            properties:
              replicas:
                type: integer
              resources:
                type: object
              version:
                type: string
            type: object
        type: object
    served: true
    storage: true 