apiVersion: v1
kind: ConfigMap
metadata:
  name: trading-bot-config
  namespace: evil2root-trading
data:
  FLASK_APP: "run.py"
  FLASK_ENV: "production"
  TZ: "UTC"
  PYTHONDONTWRITEBYTECODE: "1"
  PYTHONUNBUFFERED: "1"
  PIP_DISABLE_PIP_VERSION_CHECK: "1"
  PIP_NO_CACHE_DIR: "1" 