# PersistentVolumeClaim pour PostgreSQL
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data
  namespace: evil2root-trading
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: do-block-storage
---
# PersistentVolumeClaim pour Redis
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-data
  namespace: evil2root-trading
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: do-block-storage
---
# PersistentVolumeClaim pour les données de l'application
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: app-data
  namespace: evil2root-trading
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: do-block-storage
---
# PersistentVolumeClaim pour les logs
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: app-logs
  namespace: evil2root-trading
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: do-block-storage
---
# PersistentVolumeClaim pour les modèles sauvegardés
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: saved-models
  namespace: evil2root-trading
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: do-block-storage
---
# PersistentVolumeClaim pour Prometheus
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-data
  namespace: evil2root-trading
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: do-block-storage
---
# PersistentVolumeClaim pour Grafana
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-data
  namespace: evil2root-trading
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: do-block-storage
---
# PersistentVolumeClaim pour les sauvegardes PostgreSQL
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-backups
  namespace: evil2root-trading
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: do-block-storage 