name: Build and Push Docker Image to DigitalOcean

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Log in to DigitalOcean Container Registry
        run: doctl registry login --expiry-seconds 3600

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            registry.digitalocean.com/${{ secrets.DIGITALOCEAN_REGISTRY_NAME }}/evil2root-ai:latest
            registry.digitalocean.com/${{ secrets.DIGITALOCEAN_REGISTRY_NAME }}/evil2root-ai:${{ github.sha }}
          cache-from: type=registry,ref=registry.digitalocean.com/${{ secrets.DIGITALOCEAN_REGISTRY_NAME }}/evil2root-ai:buildcache
          cache-to: type=registry,ref=registry.digitalocean.com/${{ secrets.DIGITALOCEAN_REGISTRY_NAME }}/evil2root-ai:buildcache,mode=max
          build-args: |
            BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ')
            GIT_COMMIT=${{ github.sha }}
            
      - name: Notify build completion
        if: success()
        run: |
          echo "Image successfully built and pushed to registry.digitalocean.com/${{ secrets.DIGITALOCEAN_REGISTRY_NAME }}/evil2root-ai:latest"
          echo "Image tag: ${{ github.sha }}" 