name: Update Kubernetes Secrets

on:
  workflow_dispatch:
    inputs:
      update_secrets:
        description: 'Mettre à jour les secrets dans Kubernetes'
        required: true
        default: 'true'

jobs:
  update-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Get kubeconfig
        run: |
          doctl kubernetes cluster kubeconfig save evil2root-trading

      - name: Update Kubernetes secrets
        run: |
          # Créer le namespace s'il n'existe pas
          kubectl apply -f kubernetes/namespace.yaml

          # Créer ou mettre à jour les secrets depuis les variables d'environnement GitHub
          kubectl create secret generic trading-bot-secrets \
            --namespace=evil2root-trading \
            --from-literal=DB_USER=${{ secrets.DB_USER }} \
            --from-literal=DB_PASSWORD=${{ secrets.DB_PASSWORD }} \
            --from-literal=DB_NAME=${{ secrets.DB_NAME }} \
            --from-literal=REDIS_PASSWORD=${{ secrets.REDIS_PASSWORD }} \
            --from-literal=GRAFANA_ADMIN_USER=${{ secrets.GRAFANA_ADMIN_USER }} \
            --from-literal=GRAFANA_ADMIN_PASSWORD=${{ secrets.GRAFANA_ADMIN_PASSWORD }} \
            --dry-run=client -o yaml | kubectl apply -f -

          # Redémarrer les déploiements pour prendre en compte les nouveaux secrets
          kubectl rollout restart deployment/trading-bot-web -n evil2root-trading
          kubectl rollout restart deployment/market-scheduler -n evil2root-trading
          kubectl rollout restart deployment/analysis-bot -n evil2root-trading
          
          echo "Secrets mis à jour et déploiements redémarrés" 